//! Registers the standard library at build time:
//! - every `std/NAME.mars` becomes the bundled package `std.NAME`, and a
//!   directory is a package too: `std/file/init.mars` is `std.file` and
//!   `std/file/csv.mars` is `std.file.csv`, as for a program's own packages;
//! - every `std/rs/NAME.rs` is compiled in as the native package `rs.NAME`,
//!   which must define `pub fn package() -> crate::value::Value`.
//! Adding a file is enough; no list needs editing.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let std_dir = root.join("std");
    println!("cargo:rerun-if-changed={}", std_dir.display());
    println!("cargo:rerun-if-changed={}", std_dir.join("rs").display());

    let mut out = String::from("// Generated by build.rs from the std/ directory.\n\n");

    out.push_str("/// Standard packages written in Marslang (`std/**/*.mars`): the name, the\n");
    out.push_str("/// source, and whether it is a directory's `init.mars`.\n");
    out.push_str("pub(crate) const BUNDLED: &[(&str, &str, bool)] = &[\n");
    let mut packages = Vec::new();
    bundled(&std_dir, "std", &mut packages);
    packages.sort();
    for (name, path, is_init) in packages {
        out.push_str(&format!("    ({name:?}, include_str!({:?}), {is_init}),\n", path.display().to_string()));
    }
    out.push_str("];\n\n");

    out.push_str("/// Native packages written in Rust (`std/rs/*.rs`), compiled into the interpreter.\n");
    out.push_str("pub(crate) mod native {\n");
    let native = files(&std_dir.join("rs"), "rs");
    for (name, path) in &native {
        // pub(crate): the interpreter's own string methods share rs_string's helpers.
        out.push_str(&format!("    #[path = {:?}]\n    pub(crate) mod rs_{name};\n", path.display().to_string()));
    }
    out.push_str("\n    pub(crate) const PACKAGES: &[(&str, fn() -> crate::value::Value)] = &[\n");
    for (name, _) in &native {
        out.push_str(&format!("        (\"rs.{name}\", rs_{name}::package),\n"));
    }
    out.push_str("    ];\n}\n");

    fs::write(PathBuf::from(env::var("OUT_DIR").unwrap()).join("std_packages.rs"), out).unwrap();
}

/// Every Marslang package under `dir`, named from `prefix`. `rs/` holds the
/// native packages, not Marslang ones.
fn bundled(dir: &Path, prefix: &str, found: &mut Vec<(String, PathBuf, bool)>) {
    for (name, path) in files(dir, "mars") {
        if name == "init" {
            assert!(prefix != "std", "{}: std itself is not a package", path.display());
            found.push((prefix.to_string(), path, true));
        } else {
            found.push((format!("{prefix}.{name}"), path, false));
        }
    }
    let Ok(entries) = fs::read_dir(dir) else { return };
    let mut dirs: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).filter(|p| p.is_dir()).collect();
    dirs.sort();
    for sub in dirs {
        let name = sub.file_name().unwrap().to_string_lossy().into_owned();
        if prefix == "std" && name == "rs" { continue; }
        assert!(is_identifier(&name), "{}: package directory names must be identifiers", sub.display());
        bundled(&sub, &format!("{prefix}.{name}"), found);
    }
}

fn is_identifier(name: &str) -> bool {
    name.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// (stem, path) of files with the extension, sorted; stems must be identifiers.
fn files(dir: &Path, extension: &str) -> Vec<(String, PathBuf)> {
    let Ok(entries) = fs::read_dir(dir) else { return Vec::new() };
    let mut found: Vec<(String, PathBuf)> = entries
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().is_some_and(|e| e == extension))
        .map(|path| (path.file_stem().unwrap().to_string_lossy().into_owned(), path))
        .collect();
    for (name, path) in &found {
        assert!(is_identifier(name), "{}: package file names must be identifiers", path.display());
    }
    found.sort();
    found
}
