WHITESPACE = _{ " " | "\t" | NEWLINE }
NEWLINE = _{ "\n" | "\r\n" }
COMMENT = _{ line_comment | block_comment }
line_comment = _{ "//" ~ (!NEWLINE ~ ANY)* }
block_comment = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

program = { SOI ~ item* ~ EOI }
item = _{ import_decl | var_decl | func_decl | family_decl | stmt }

import_decl = { "takepkg" ~ ident ~ ("=" ~ ident)? ~ ";" }

var_decl = { fixed_kw? ~ temp_kw? ~ ident ~ type_ann? ~ "=" ~ expr ~ ";" }
fixed_kw = { "fixed" }
temp_kw = { "hot" | "cold" }
type_ann = { "(" ~ type_name ~ ")" }
type_name = @{ (!")" ~ ANY)+ }

func_decl = { "func" ~ ident ~ params? ~ (func_expr_body | func_block_body) ~ ";"? }
params = { "(" ~ param* ~ ")" }
param = { type_name_atom ~ ident ~ ";" }
type_name_atom = @{ (!(";" | " " | "\t" | NEWLINE | ")") ~ ANY)+ }
func_expr_body = { "=>" ~ expr ~ ";" }
func_block_body = { block }

family_decl = { "family" ~ ident ~ ("(" ~ ident ~ ")")? ~ "{" ~ func_decl* ~ "}" ~ ";"? }

stmt = _{ var_decl | ret_stmt | if_stmt | repeat_stmt | assign_stmt | expr_stmt }
ret_stmt = { "ret" ~ expr ~ ";" }
if_stmt = { "if" ~ "(" ~ expr ~ ")" ~ block ~ elif_stmt* ~ else_stmt? }
elif_stmt = { "elif" ~ "(" ~ expr ~ ")" ~ block }
else_stmt = { "else" ~ block }
repeat_stmt = { "repeat" ~ expr ~ block }
assign_stmt = { member_or_ident ~ "=" ~ expr ~ ";" }
expr_stmt = { expr ~ ";" }
block = { "{" ~ stmt* ~ "}" }

expr = { binary_expr }
binary_expr = { call_expr ~ (op ~ call_expr)* }
op = _{ "==" | "!=" | "<=" | ">=" | "<" | ">" | "+" | "-" | "*" | "/" | "%" | "**" }

call_expr = { primary_expr ~ call_suffix* }
call_suffix = { "(" ~ arg_list? ~ ")" }
arg_list = { expr ~ ("," ~ expr)* }
primary_expr = { member_or_ident | number | string | bool | null | "(" ~ expr ~ ")" }
member_or_ident = { ident ~ ("." ~ ident)* }

number = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
string = @{ "\"\"\"" ~ (!"\"\"\"" ~ ANY)* ~ "\"\"\"" | "\"" ~ ("\\\"" | !"\"" ~ ANY)* ~ "\"" | "'" ~ ("\\'" | !"'" ~ ANY)* ~ "'" }
bool = { "true" | "false" | "fasle" }
null = { "null" }
ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_" )* }
